/*
 * Copyright 2018 Dmitriy Malakhov.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.stagirs.wiki.parser.text;

import com.github.stagirs.wiki.model.WikiText;
import com.github.stagirs.wiki.model.text.WikiTag;
import com.github.stagirs.wiki.parser.WikiTextParser;
import static org.junit.Assert.assertEquals;
import org.junit.Test;

/**
 *
 * @author Dmitriy Malakhov
 */
public class TagParserTest {
    
    @Test
    public void test1(){
        WikiText text = WikiTextParser.get(0, "<small>Здание факультета ВМК МГУ, построенное в 1978 году</small>");
        WikiTag tag = text.getTags().get(0);
        assertEquals(tag.getName(), "small");
        assertEquals(tag.getBody().getRawText(), "Здание факультета ВМК МГУ, построенное в 1978 году");
    }
    
    @Test
    public void test2(){
        WikiText text = WikiTextParser.get(0, "<ref name=autogenerated1 />");
        WikiTag tag = text.getTags().get(0);
        assertEquals(tag.getName(), "ref");
        assertEquals(tag.getBody().getRawText(), "");
        assertEquals(tag.getAttrs().get("name"), "autogenerated1");
    }
    
    @Test
    public void test3(){
        WikiText text = WikiTextParser.get(0, "<ref name=autogenerated2>[https://cs.msu.ru/departments/om Кафедра общей математики — сайт ВМК МГУ]</ref>");
        WikiTag tag = text.getTags().get(0);
        assertEquals(tag.getName(), "ref");
        assertEquals(tag.getBody().getRawText(), "[https://cs.msu.ru/departments/om Кафедра общей математики — сайт ВМК МГУ]");
        assertEquals(tag.getAttrs().get("name"), "autogenerated2");
    }
    
    @Test
    public void test4(){
        WikiText text = WikiTextParser.get(0, "<br>");
        WikiTag tag = text.getTags().get(0);
        assertEquals(tag.getName(), "br");
        assertEquals(tag.getBody().getRawText(), "");
    }
    
    @Test
    public void test5(){
        {
            WikiText text = WikiTextParser.get(0, "<span style=\"color:#090;\">очень высокий</span>");
            WikiTag tag = text.getTags().get(0);
            assertEquals(tag.getName(), "span");
            assertEquals(tag.getBody().getRawText(), "очень высокий");
            assertEquals(tag.getAttrs().get("style"), "color:#090;");
        }
        {
            WikiText text = WikiTextParser.get(0, "<span style='color:#090;'>очень высокий</span>");
            WikiTag tag = text.getTags().get(0);
            assertEquals(tag.getName(), "span");
            assertEquals(tag.getBody().getRawText(), "очень высокий");
            assertEquals(tag.getAttrs().get("style"), "color:#090;");
        }
    }
}
